pull_request_rules:
  - name: Automatic merge on CI success
    conditions:
      - author=pyup[bot]
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
