matrix:
  include:
    - language: node_js
      node_js:
        - "8.12.0"
        - "node"
      install:
        - npm install -g vue-cli
        - npm install --save-dev jest jest-vue-preprocessor babel-jest jsdom vue-server-renderer
#      stages:
#        - lint
#        - test
#        - build
      script: npm run unit
notifications:
  email:
    on_failure: change # default: always
#      jobs:
#        include:
#          - stage: lint
#            script:
#              # Run linter
#              - npm run lint
#          - stage: test
#            script:
#              # Run tests
#              - npm run unit
##          - stage: build
##            script:
##              # Build all
##              - npm run build:docs
##              - npm run build:system
##              - npm run build:app
#
